TRPO-Lab5.AspNetApplication/Models/CalculationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static TRPO_Lab3.Lib.CylinderArea;

namespace TRPO_Lab5.AspNetApplication.Models
{
    public class CalculationViewModel
    {
        public const double PI = 3.14;

        public double Radius { get; set;}

        public double Height { get; set; }

        public double Area { get; set; }

    }
}

TRPO-Lab5.AspNetApplication/Models/ErrorViewModel.cs
using System;

namespace TRPO_Lab5.AspNetApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TRPO-Lab5.AspNetApplication/Controllers/CalculationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TRPO_Lab5.AspNetApplication.Models;
using static TRPO_Lab3.Lib.CylinderArea;

namespace TRPO_Lab5.AspNetApplication.Controllers
{
    public class CalculationController : Controller
    {
        [HttpGet]
        public ActionResult Calc()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Calc(string R, string H)
        {
            double area = GetCylinderArea(Convert.ToDouble(R), Convert.ToDouble(H));
            ViewBag.Result = Math.Round(area, 3) + " у. ед.";
            return View();
        }
    }
}

TRPO-Lab5.AspNetApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TRPO_Lab5.AspNetApplication.Models;

namespace TRPO_Lab5.AspNetApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TRPO-Lab5.AspNetApplication/Views/Calculation/Calc.cshtml
@{ 
    IgnoreBody(); 
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TRPO_Lab5.AspNetApplication</title>
    <link rel="stylesheet" href="~/css/calc.css" />
</head>
<body>
    <main>
        <h1 class="main__header">Площадь поверхности цилиндра</h1>
        <img class="main__cylinder" src="~/img/cilinder_surface_area.png" alt="Cylinder Surface Area" />
        <img class="main__formula" src="~/img/surface_area_formula.png" alt="Cylinder Surface Formula" />
        <form class="main__form" action="" method="post">
            <div>
                <span class="form__unvalid">Необходимо использовать только положительные значения</span>
                <input class="form__input" type="number" name="R" placeholder="Радиус, R" />
                <input class="form__input" type="number" name="H" placeholder="Высота, H" />
                <button class="form__btn" asp-area="" asp-controller="Calculation" asp-action="Calc">Рассчитать</button>
                <p class="form__result">Результат: @ViewBag.Result</p>
            </div>
        </form>
    </main>

    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

TRPO-Lab5.AspNetApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TRPO-Lab5.AspNetApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TRPO_Lab5.AspNetApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TRPO_Lab5.AspNetApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculation" asp-action="Calc">Calculate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TRPO_Lab5.AspNetApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>